<?
$PERM["testing.php"]["*"]="D";
$PERM["testing.php"]["6"]="X";
$PERM["catalog"]["7"]="W";
$PERM["upload"]["8"]="T_8";
$PERM["personal"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>